[package]
name = "playground"
version = "0.1.0"
edition = "2021"

[build-dependencies]
cc = "1.2.21"

[dependencies]
p3-mersenne-31.workspace = true
p3-monolith.workspace = true
rand.workspace = true
memmap2 = "0.9.5"
cty = "0.2.2"
